"""cash table

Revision ID: 7c305ec405a0
Revises: 70346826d8a7
Create Date: 2018-03-06 17:56:43.772929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c305ec405a0'
down_revision = '70346826d8a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash', sa.Float(precision=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cash')
    # ### end Alembic commands ###
